steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['package', '-Dmaven.skip.test=true']

#build docker container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/devops-297210/petclinic', '--build-arg=JAR_FILE=target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar', '.']

#push container to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/devops-297210/petclinic']
  
#deploy to cloud run
- name: 'gcr.io/cloud-builders/gcloud1'
  args:
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - 'gcr.io/devops-297210/petclinic:latest'
  - '--region'
#  - 'us-central1'
  - 'europe-west3'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
  - 'gcr.io/devops-297210/petclinic:'latest'
